### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by KrisThielemans** [ismrmrd/ismrmrd-python#11]
I cannot find any installation instructions nor list of dependencies. It'd be great to have a place somewhere that says to install pyxb and Cython. The following worked for me on Ubuntu 12.04

```
sudo pip install pyxb
sudo pip install Cython --upgrade
sudo python setup.py install 
```

(I needed to upgrade Cython as the Ubuntu 12.04 cython package didn't compile ismrmrd-pythom)

**Comment by SanNicoSan** [comment]
Where you able to install this package?
I'm trying to install it from Google Colab and had no succes.
Let me know if you managed to solve the issue
