### ISSUE TITLE
AttributeError: 'Acquisition' object has no attribute 'head'

### ISSUE THREAD

**Issue by zwep** [ismrmrd/ismrmrd-python#22]
This is the error I get when I try the example/demo file

https://github.com/ismrmrd/ismrmrd-python/blob/master/examples/demo.py

In the 1.6.1 version of this package, I believe it should be

acq.getHead().version = 42

Also, I think that the piece of code 

print f.filename

should be changed to

print(f._file)

because filename is no attribute of f.

**Comment by dchansen** [comment]
You're right. The demo hadn't been updated in quite a while. I've updated it to the correct syntax
