### ISSUE TITLE
usage issue

### ISSUE THREAD

**Issue by zwep** [ismrmrd/ismrmrd-python#24]
Hello,

I have obtained my raw/lab/sin files from the scanner. Converted these to ismrmrd-.h5 format with the philips_to_ismrmrd commandline tool provided by this repo as well.

Next, my idea was to inspect the content of these .h5-files using the ismrmrd-python library. From the python/example.. I assumed that it would "as easy as" executing

> f = ismrmrd.Dataset(i_file, '/dataset', True)
> f.read_image('data', 0)

However, this is not the case. The function read_image does not check whether the 'header' and 'attributes' key are there. Neither does it do anything to take action when they are not there. So I ended up with an error there.

Taking a closer look at the code.. I thought maybe I can fix this myself. Since the following code executed perfectly

> f.read_acquisition(0)
> f.read_xml_header()

And since those two things are what is "missing", I thought maybe I can come up with a substitute myself.

It seems that the part to 'read in the data' is done by declaring the following variable

> self.__data = np.empty(shape=(self.__head.channels, self.__head.matrix_size[2],
                                          self.__head.matrix_size[1], self.__head.matrix_size[0]),
                                   dtype=get_dtype_from_data_type(self.__head.data_type))

Which is later used as

> im.data[:] = self._dataset[impath]['data'][imnum]

But even if I got the definition of self._data right (for example.. (24, 1, 256, 256)). Then still, running the line above would result in a broadcasting error. Only a line like 

> im.data.ravel()[:] = self._dataset[impath]['data'][imnum]

would be able to do it correctly, since the data coming from the .h5 file is a 1-dimensional vector.

Enfin. I can't read in the data provided by the philips_to_ismrmrd with the ismrmrd-python tool. Probably Im on a wrong track. But I don't know enough HOW the data is stored inside the .h5 tool to fix it myself.
The datastructure looks quite daunting to figure it out myself.. so maybe you have some pointers on where to start...

**Comment by hansenms** [comment]
Picking this up after it has been idle for some time. Could you let us know if you managed to resolve this issue. If not, please provide a dataset and a set of commands that you did so that we can reproduce this issue. 

In general, if you take a raw dataset from a raw data converter. I would not expect you to be able to load any images, since there would be none. `read_acquisition` and `read_xml_header` is what I would expect to work. So can you please clarify what you are expecting?

We will keep this open for another week or so and then close if inactive.

**Comment by zwep** [comment]
Yeah closing this is fine, it has been three years... so yeah....
