### ISSUE TITLE
Package depends on PyXB which is at end-of-life

### ISSUE THREAD

**Issue by mmuckley** [ismrmrd/ismrmrd-python#30]
One of the dependencies includes `pyxb`, which as noted by the maintainer is at [end-of-life](https://github.com/pabigot/pyxb/issues/100), and other solutions are recommended.

Perhaps the most pressing item is that `pyxb` has a deprecated idiom for importing from `collections`: [PR 111](https://github.com/pabigot/pyxb/pull/111). This is a warning that has been showing up in my tests.

I just tested ISMRMRD in Python 3.9 and I think it's still working despite the deprecation, but long-term stability of the Python ISMRMRD package could still be threatened by this dependency.

The best solution would probably be to remove the need for `pyxb` from `ismrmrd`. If this isn't possible, then perhaps `ismrmrd` could create its own fork of `pyxb` and merge [PR 111](https://github.com/pabigot/pyxb/pull/111).

**Comment by dchansen** [comment]
This was fixed a while back. Sorry for not replying sooner
