### ISSUE TITLE
ImportError: cannot import name 'OutputFormat' from 'xsdata.models.config'

### ISSUE THREAD

**Issue by kspaceKelvin** [ismrmrd/ismrmrd-python#35]
The current code using xsdata fails to pass setup install with the error message:
```
  File "/opt/code/ismrmrd-python/setup.py", line 25, in run
    generate_schema(schema_file, config_file, outloc)
  File "/opt/code/ismrmrd-python/setup.py", line 48, in generate_schema
    from xsdata.models.config import OutputFormat
ImportError: cannot import name 'OutputFormat' from 'xsdata.models.config' (/usr/local/lib/python3.9/site-packages/xsdata/models/config.py)
```

To replicate, use the following Dockerfile:
```
FROM python:3.9-slim

RUN apt-get update && apt-get install -y git
RUN pip install --no-cache-dir h5py xsdata jinja2 toposort docformatter
RUN mkdir -p /opt/code

RUN  cd /opt/code \
     && git clone https://github.com/ismrmrd/ismrmrd-python.git \
     && cd /opt/code/ismrmrd-python \
     && python3 setup.py install
```

@dchansen Is there something obvious that I'm missing in getting this to run?  Removing this import and manually setting ``config.output.format`` to ``"pydata"`` doesn't seem to fix this either.

@hansenms Should we also set up a Github build workflow for this to make sure that we can catch these in the future?  Happy to copy from the siemens_to_ismrmrd one so I can learn how to do so.

**Comment by dchansen** [comment]
@kspaceKelvin We were using some APIs from xsdata which turned out to be internal, and thus subject to change. I've updated Ismrmrd to use  the command line interface instead. 

You would want to run pip to install the package, rather than setup.py.

```
FROM python:3.9-slim

RUN apt-get update && apt-get install -y git
RUN mkdir -p /opt/code

RUN  cd /opt/code \
     && git clone https://github.com/ismrmrd/ismrmrd-python.git \
     && cd /opt/code/ismrmrd-python \
     && pip install . 
```

**Comment by kspaceKelvin** [comment]
@dchansen Great, thanks for the quick patch and the background!  Happy to pip install instead -- looks like I'm out of date with my Python best practices.  Any thoughts on my adding an automated Docker build workflow?
