### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by 872520333** [ismrmrd/ismrmrd-python#43]
Could you please help me to solve it? Thanks!

(pytorch1.7.1) jiale@gdp-SYS-7049GP-TRT:~/ismrmrd-python-master$ python setup.py install
running install
running bdist_egg
running egg_info
writing ismrmrd.egg-info/PKG-INFO
writing dependency_links to ismrmrd.egg-info/dependency_links.txt
writing requirements to ismrmrd.egg-info/requires.txt
writing top-level names to ismrmrd.egg-info/top_level.txt
reading manifest file 'ismrmrd.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ismrmrd.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
/data3/jiale/anaconda3/envs/pytorch1.7.1/bin/python: No module named xsdata
error: [Errno 2] No such file or directory: 'ismrmrdschema/__init__.py'

**Comment by hansenms** [comment]
You have not installed xsdata. Do `pip3 install xsdata[cli]==22.2` before running setup install. 

In general, we recommend just installing as a pip package to avoid this issue:

````
pip3 install ismrmrd==1.9.8
```
