### ISSUE TITLE
Reading entire mrd file without loop

### ISSUE THREAD

**Issue by aghaeifar** [ismrmrd/ismrmrd-python#65]
Hi,

I am trying to import a whole brain data with 13 repetitions (almost a large rawdata). It is pretty slow when I use `for loop` and read acquisitions one by one. Is there an alternative to read entire acquisitions without looping? ismrmrd MATLAB wrapper simply does it if readAcquisition() is called without an argument. Can we do something similar in ismrmrd Python interface? if not, can you please advise how to import a large mrd file faster?
in my experiment, importing entire data in MATLAB is ~20x faster than `for loop` in Python.

Thank you.
Ali

**Comment by aghaeifar** [comment]
I tried to read mrd file with h5py library and could read entire data at once. The elapsed time was similar to MATLAB (slightly less). Here is the code that I used:
```
import h5py
with h5py.File(filename, "r") as mrd:
    if len(mrd.keys()) > 1:
        print('MRD file has more than one group. The last group will be imported.')
    dataset_name = list(mrd.keys())[-1]
    data_struct  = mrd[dataset_name]['data'][:]
    xml_struct   = mrd[dataset_name]['xml'][0]
    hdr          = data_struct['head']
    data         = data_struct['data']

header  = ismrmrd.xsd.CreateFromDocument(xml_struct)
```

**Comment by dchansen** [comment]
You should be able to read it in fairly quickly using the File interface:

`import ismrmrd
with ismrmrd.File(filename) as mrd:
    acqs = mrd['dataset'].acquisitions[:]
`

On my 10Gb dataset, this is about ~5x faster than Matlab, but your mileage may vary.

**Comment by aghaeifar** [comment]
Good to know about File interface. Thanks, David.
This is now much faster than loop. (in my 4Gb dataset, MATLAB is still slightly faster (~7.5sec vs ~6.5sec)).

**Comment by dchansen** [comment]
That's interesting. Is it possible for you to share the code/data?

**Comment by aghaeifar** [comment]
Sure,
mrd file: https://owncloud.tuebingen.mpg.de/index.php/s/2mfYinijmixzyeJ

MATALB
```
filename = '/DATA/meas_MID00047_FID27956_aa_B0Mapping_2ndorder_IECO.mrd';
dset = ismrmrd.Dataset(filename, 'dataset_1');
tic
data_struct   = dset.readAcquisition();
this.hdr.head = data_struct.head;
toc
dset.close()
```

Python
```
import ismrmrd
import time

filename = '/DATA/meas_MID00047_FID27956_aa_B0Mapping_2ndorder_IECO.mrd'
start = time.time()
with ismrmrd.File(filename) as mrd:
    acqs = mrd['dataset_1'].acquisitions[:]
print(time.time() - start)
```

**Comment by dchansen** [comment]
Thanks for sharing this. Are you testing Matlab on linux? 
The numbers I'm seeing on Windows are ~50s for Matlab, and ~11s for python.

**Comment by aghaeifar** [comment]
Thank you for checking.
Yes, I tested on Ubuntu 22.04
on a different PC with Windows, Matlab was slower than Python (~50s  vs ~18s ). Interesting!
